package com.geneza.lms.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;
import java.math.*;
import java.time.LocalDateTime;

import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * Assignment Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "Assignment")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "GenezaRest/com/geneza/lms/domain", name = "Assignment")
public class Assignment implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    @Column(name = "assignment")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String assignment;
    
    @Column(name = "content", columnDefinition = "TEXT")
    private String assignmentContent;

    @Column(name = "assignmentKey", columnDefinition = "TEXT")
    private String assignmentKey;
    
    @ManyToOne
    @JoinColumn(name="module")
    private Module module;

    @Column(name = "durationDays")
    private Integer durationDays;

    @Column(name = "archivedAt")
    private LocalDateTime archivedAt;

    @Column(name = "contentRequired")
    private Boolean contentRequired;

    @Column(name = "attachmentRequired")
    private Boolean attachmentRequired;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getAssignment() {
        return assignment;
    }
    
    public void setAssignment(String assignment) {
        this.assignment = assignment;
    }
    
    public Module getModule() {
        return module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    
    public String getAssignmentContent() {
        return assignmentContent;
    }
    
    public void setAssignmentContent(String assignmentContent) {
        this.assignmentContent = assignmentContent;
    }
    
    public String getAssignmentKey() {
        return assignmentKey;
    }
    
    public void setAssignmentKey(String assignmentKey) {
        this.assignmentKey = assignmentKey;
    }

    public Integer getDurationDays() {
        return durationDays;
    }

    public void setDurationDays(Integer durationDays) {
        this.durationDays = durationDays;
    }

    public LocalDateTime getArchivedAt() {
    return archivedAt;
    }

    public void setArchivedAt(LocalDateTime archivedAt) {
        this.archivedAt = archivedAt;
    }

    public Boolean getContentRequired() {
        return contentRequired;
    }

    public void setContentRequired(Boolean contentRequired) {
        this.contentRequired = contentRequired;
    }

    public Boolean getAttachmentRequired() {
        return attachmentRequired;
    }

    public void setAttachmentRequired(Boolean attachmentRequired) {
        this.attachmentRequired = attachmentRequired;
    }

    public Assignment() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof Assignment))
            return false;
        Assignment equalCheck = (Assignment) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}