package com.geneza.lms.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * AssignmentSubmission Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "assignmentsubmission",uniqueConstraints = @UniqueConstraint(columnNames = {"assignment", "enrollment"}))
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "GenezaRest/com/geneza/lms/domain", name = "assignmentsubmission")
public class AssignmentSubmission implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;
    
    @Column(name = "content")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String submissionContent;

    @Column(name = "comment")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String comment;

    @ManyToOne
    @JoinColumn(name="assignment")
    private Assignment assignment;@ManyToOne
    @JoinColumn(name="enrollment")
    private Enrollment enrollment;@ManyToOne
    @JoinColumn(name="submissionStatus")
    private SubmissionStatus submissionStatus;

    @Column(name = "file_url")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String fileUrl;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Assignment getAssignment() {
        return assignment;
    }
    
    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }
    
    public Enrollment getEnrollment() {
        return enrollment;
    }
    
    public void setEnrollment(Enrollment enrollment) {
        this.enrollment = enrollment;
    }
    
    public String getSubmissionContent() {
        return submissionContent;
    }
    
    public void setSubmissionContent(String submissionContent) {
        this.submissionContent = submissionContent;
    }

    public String getComment() {
        return comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    public SubmissionStatus getSubmissionStatus() {
        return submissionStatus;
    }
    
    public void setSubmissionStatus(SubmissionStatus submissionStatus) {
        this.submissionStatus = submissionStatus;
    }


    public AssignmentSubmission() {
    }

    public String getFileUrl() {
        return fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }
    


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof AssignmentSubmission))
            return false;
        AssignmentSubmission equalCheck = (AssignmentSubmission) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}