package com.geneza.lms.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * BatchSurvey Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "BatchSurvey")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "GenezaRest/com/geneza/lms/domain", name = "BatchSurvey")
public class BatchSurvey implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "surveyId")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer surveyId;

    @Column(name = "receipientRole")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String receipientRole;

    @Column(name = "linkRole")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String linkRole;

    

    
    
    @ManyToOne
    @JoinColumn(name="batchId")
    private Batch batch;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Integer getSurveyId() {
        return surveyId;
    }
    
    public void setSurveyId(Integer surveyId) {
        this.surveyId = surveyId;
    }
    
    public Batch getBatch() {
        return batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    
    public String getReceipientRole() {
        return receipientRole;
    }
    
    public void setReceipientRole(String receipientRole) {
        this.receipientRole = receipientRole;
    }
    
    public String getLinkRole() {
        return linkRole;
    }
    
    public void setLinkRole(String linkRole) {
        this.linkRole = linkRole;
    }

    


    public BatchSurvey() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof BatchSurvey))
            return false;
        BatchSurvey equalCheck = (BatchSurvey) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}