package com.geneza.lms.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * CompetencyCriterion Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "competencycriterion")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "GenezaRest/com/geneza/lms/domain", name = "competencycriterion")
public class CompetencyCriterion implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "comptenecyCriterion")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String comptenecyCriterion;
    
    
    @ManyToOne
    @JoinColumn(name="competencyCategoryId")
    private CompetencyCategory competencyCategory;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getComptenecyCriterion() {
        return comptenecyCriterion;
    }
    
    public void setComptenecyCriterion(String comptenecyCriterion) {
        this.comptenecyCriterion = comptenecyCriterion;
    }
    
    public CompetencyCategory getCompetencyCategory() {
        return competencyCategory;
    }
    
    public void setCompetencyCategory(CompetencyCategory competencyCategory) {
        this.competencyCategory = competencyCategory;
    }


    public CompetencyCriterion() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof CompetencyCriterion))
            return false;
        CompetencyCriterion equalCheck = (CompetencyCriterion) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}