package com.geneza.lms.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * DailyUpdateModule Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "dailyUpdateModule")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "GenezaRest/com/geneza/lms/domain", name = "dailyUpdateModule")
public class DailyUpdateModule implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    
    
    
    @ManyToOne
    @JoinColumn(name="dailyUpdateId")
    private DailyUpdate dailyUpdate;
    
    @ManyToOne
    @JoinColumn(name="moduleId")
    private BatchModule module;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public DailyUpdate getDailyUpdate() {
        return dailyUpdate;
    }
    
    public void setDailyUpdate(DailyUpdate dailyUpdate) {
        this.dailyUpdate = dailyUpdate;
    }
    
    public BatchModule getModule() {
        return module;
    }
    
    public void setModule(BatchModule module) {
        this.module = module;
    }


    public DailyUpdateModule() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof DailyUpdateModule))
            return false;
        DailyUpdateModule equalCheck = (DailyUpdateModule) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}