package com.geneza.lms.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * DailyUpdate Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "dailyUpdate")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "GenezaRest/com/geneza/lms/domain", name = "dailyUpdate")
public class DailyUpdate implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "date")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Date date;

    @Column(name = "field1")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String field1;

    @Column(name = "field2")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String field2;

    @Column(name = "field3")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String field3;
    
    
    @ManyToOne
    @JoinColumn(name="batchId")
    private Batch batch;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Batch getBatch() {
        return batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    
    public Date getDate() {
        return date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    public String getField1() {
        return field1;
    }
    
    public void setField1(String field1) {
        this.field1 = field1;
    }
    
    public String getField2() {
        return field2;
    }
    
    public void setField2(String field2) {
        this.field2 = field2;
    }
    
    public String getField3() {
        return field3;
    }
    
    public void setField3(String field3) {
        this.field3 = field3;
    }


    public DailyUpdate() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof DailyUpdate))
            return false;
        DailyUpdate equalCheck = (DailyUpdate) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}